// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Release_WebApi.Data;

#nullable disable

namespace Release_WebApi.Migrations
{
    [DbContext(typeof(ReleaseContext))]
    partial class ReleaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Release_WebApi.Models.Release", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("avulso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("data")
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("releases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            avulso = "Válido",
                            data = new DateTime(2023, 10, 30, 19, 33, 17, 458, DateTimeKind.Local).AddTicks(1790),
                            descricao = "Teste 1",
                            status = "Válido",
                            valor = 10m
                        },
                        new
                        {
                            Id = 2,
                            avulso = "Não Avulso",
                            data = new DateTime(2023, 10, 30, 19, 33, 17, 458, DateTimeKind.Local).AddTicks(1824),
                            descricao = "Teste 2",
                            status = "Cancelado",
                            valor = 20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
